# Site settings
title: songlee's room
email: 920_226@naver.com
url: https://songlee26.github.io/
#description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
description: "Mandoo's friends"
#keywords: "your keywords, separated by commas"
keywords: "Illustration,Animal,Artist,songlee,Mandoo"
skills: "Animal Illustration - songlee"
meta_author: Songlee Cho

# Google webmaster tools
google_verify: Animal Illustration

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify: Animal Illustration

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: songlee

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Songlee Cho Corp. 
  location: Location
  social: Social
#  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/_slcho/
  - title: facebook
    url: https://www.instagram.com/_slcho/
  - title: stack-overflow
    url: https://www.instagram.com/_slcho/
  - title: bitbucket
    url: https://www.instagram.com/_slcho/
  - title: github
    url: https://www.instagram.com/_slcho/

# Postal address (add as many lines as necessary)
address:
  - line: Seoul,
  - line: Republic of Korea

# Credits content
#credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'
#credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

theme: jekyll-theme-architect
